spring:
  config:
    import: optional:file:./.env[.properties]
#    import: optional:file:.env[.properties],optional:file:ops/.env[.properties]
  application:
    name: contentful-proxy
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  cache:
    type: caffeine

contentful:
#  graphql-url: https://graphql.contentful.com/content/v1/spaces/<space-id>/environments/<env>
  graphql-url: ${CONTENTFUL_GRAPHQL_URL:}
  space-id: ${CONTENTFUL_SPACE_ID:}
  access-token: ${CONTENTFUL_ACCESS_TOKEN:}
  environment: ${CONTENTFUL_ENVIRONMENT:master}
  default-locale: ${CONTENTFUL_DEFAULT_LOCALE:en-US}

cache:
  ttl-minutes: 10
  max-size: 1000
  ttl-overrides:
    tour: 5
    region: 15
    category: 30
    onboarding: 60
    home: 15
    pointOfInterest: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    al.bruno.walks: DEBUG
    org.springframework.graphql: INFO